# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-07 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratneshapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=50)),
                ('phonenumber', models.IntegerField()),
                ('password', models.CharField(max_length=50)),
                ('picture', models.FileField(upload_to='pictures')),
            ],
            options={
                'db_table': 'register',
            },
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.RemoveField(
            model_name='ratneshpy',
            name='online',
        ),
        migrations.DeleteModel(
            name='Online',
        ),
        migrations.DeleteModel(
            name='RatneshPy',
        ),
    ]
